services:
  db:
    image: postgres:16.10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$${POSTGRES_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    volumes:
      - db_data:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.2.3
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m10s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data
  # Kafka cluster with debezium for indexation elasticsearch
  # Kafka cluster
  kafka-broker-reindex:
    image: quay.io/debezium/kafka:latest
    ports:
      - 9096:9096
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-reindex:9092,EXTERNAL://${HOSTNAME:-localhost}:9096
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-reindex:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_PARTITIONS: 1
    healthcheck:
      test: [ "CMD", "/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 60s
    volumes:
      - kafka_reindex_data_1:/kafka/data
      - kafka_reindex_log_1:/kafka/logs
      - kafka_reindex_config_1:/kafka/config
  # Kafka connect with debezium
  debezium-reindex:
    image: quay.io/debezium/connect:3.3.2.Final
    ports:
      - 9083:8083
    depends_on:
      kafka-broker-reindex:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: kafka-broker-reindex:9092
      GROUP_ID: ${KAFKA_CLUSTER_ID}
      CONFIG_STORAGE_TOPIC: debezium_configs
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_statuses
    healthcheck:
      test: [ "CMD", "curl", "-s", "http://localhost:8083/" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
    volumes:
      - debezium_reindex_data_1:/kafka/data
      - debezium_reindex_log_1:/kafka/logs
      - debezium_reindex_config_1:/kafka/config

volumes:
  db_data:
  elastic_search_data:
  kafka_reindex_data_1:
  kafka_reindex_log_1:
  kafka_reindex_config_1:
  debezium_reindex_data_1:
  debezium_reindex_log_1:
  debezium_reindex_config_1: